services:
  - type: web
    name: greencart
    env: python
    buildCommand: pip install -r requirements.txt && python seed_data.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
